#%RAML 1.0
title: 426 REST API
mediaType: application/json
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://127.0.0.1:8080/api/v1/ # really should be {version}, but parsing lib doesn't support :(

types:
  User:
    type: object
    properties:
      _id:
        type: string # primary key of entity
        required: false
      first_name:
        type: string
        required: true
      last_name:
        type: string
        required: true
      birthdate:
        type: date-only
        required: true
      email:
        type: string
        required: true
        pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
      password:
        type: string
        required: true
      height:
        type: integer # will store in metric (allow imperial unit, do conversion)
        required: false
      unit:
        enum: [ imperial, metric ]
        required: true
        default: imperial
  Goal:
    type: object
    properties:
      _id:
        type: string # primary key of entity
        required: true
      context:
        type: string # dot deleimitted string that defines goal context intake.min
        required: true
      target_val:
        type: integer # quantifiable value goal defined by the user
        required: true
  Weight:
    type: object
    properties:
      _id: # not really needed could be user id and date (user_id derived from token)
        type: string # primary key of entity
        required: true
      user_id:
        type: string
        required: true
      entry_date:
        type: date-only # auto or set
        required: true
      value:
        type: number # in metric Kilograms
        format: float
        required: true
  Water:
    type: object
    properties:
      _id: # not really needed could be user id and date (user_id derived from token)
        type: string # primary key of entity
        required: true
      user_id:
        type: string
        required: true
      entry_date:
        type: date-only # auto or set
        required: true
      value:
        type: number # in metric militers
        format: float
        required: true
  Mindfulness:
    type: object
    properties: 
      _id: # not really needed could be user id and date (user_id derived from token)
        type: string # primary key of entity
        required: true
      user_id:
        type: string
        required: true
      start_datetime:
        type: datetime
        required: true
      end_datetime:
        type: datetime
        required: true
      minutes:
        type: integer
        required: false
      notes:
        type: string
        required: false
  Sleep:
    type: object
    properties:
      _id:
        type: string # primary key of entity
        required: true # not really needed could be user id and date (user_id derived from token)
      user_id:
        type: string
        required: true
      start_datetime:
        type: datetime
        required: true
      end_datetime:
        type: datetime
        required: true
      minutes:
        type: integer
        required: false
      quality:
        type: integer
        required: false
        minimum: 0
        maximum: 10
      notes:
        type: string
        required: false

securitySchemes:
  jwt:
    type: x-jwt
/test:
  post:
    displayName: test
    securedBy: jwt
    body:
      application/json:
        properties:
          hello:
            type: string
            required: true
/users:
  post:
    displayName: user.create
    description: Create a new user
    body:
      type: User
    responses:
      201:
        body:
          application/json:
            type: User
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  /login:
    post:
      displayName: user.login
      description: Login user
      body:
        application/json:
          properties:
            email:
              type: string
              required: true
              pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
            password:
              type: string
              required: true
      responses:
        200:
        401:
          body:
            application/json:
  /me:
    get:
      displayName: user.profile
      description: User profile information
      securedBy: jwt
      queryParameters:
          fields:
            description: Specify the fields that you want to retrieve
            type:        string
            required:    false
            example:     start_datetime, end_datetime
      responses:
        200:
          body:
            application/json:
              type: User
        404:
          body:
            application/json:
        400:
          body:
            application/json:
              example: |
                {
                  "errors": [{
                    "type": "<string>",
                    "dataPath": "<string.deleimitted>",
                    "message": "<string>"
                  }]
                }
              properties:
                errors:
                  type: array

    delete:
      displayName: user.delete
      description: Delete user
      securedBy: jwt
      responses:
        202:
        404:
        400:
          body:
            application/json:
    /renew:
      post:
        displayName: user.renew
        description: Renew user's token
        securedBy: jwt
        responses:
          200:
          401:
            body:
              application/json:
    /verify:
      post:
        displayName: user.verify
        description: Check authenticity of user's token
        securedBy: jwt
        responses:
          204:
          401:
    /logout:
      post:
        displayName: user.logout
        description: Logout user, removes cookie if present
        securedBy: jwt
        responses:
          204:
          401:
/weight:
  get:
    displayName: weight.list
    description: Create a new weight resource
    securedBy: jwt 
    queryParameters:
      page:
        description: Specify the page that you want to retrieve
        type:        integer
        required:    true
        example:     1
      per_page:
        description: Specify the amount of items that will be retrieved per page
        type:        integer
        minimum:     10
        maximum:     200
        default:     30
        example:     50
    responses:
      200:
        body:
          application/json:
            type: Weight[]
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  post:
    displayName: weight.create
    description: Create a new weight resource
    securedBy: jwt 
    body:
      properties: # Don't need the other properties because JWT tells us
        entry_date:
          type: date-only # auto or set
          required: true
        value:
          type: integer # in metric
          required: true
    responses:
      200:
        body:
          application/json:
            type: Weight
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  /{_id}:
    get:
        displayName: weight.read
        description: Get weight with _id
        securedBy: jwt
        queryParameters:
          fields:
            description: Specify the fields that you want to retrieve
            type:        string
            required:    false
            example:     start_datetime, end_datetime
        responses:
          200:
            body:
              application/json:
                type: Weight
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    patch:
        displayName: weight.update
        description: Update weight with _id
        securedBy: jwt
        body:
          application/json:
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    delete:
        displayName: weight.delete
        description: Delete weight with _id
        securedBy: jwt
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
/water:
  get:
    displayName: water.list
    description: Create a new water resource
    securedBy: jwt 
    queryParameters:
      page:
        description: Specify the page that you want to retrieve
        type:        integer
        required:    false
        example:     1
      per_page:
        description: Specify the amount of items that will be retrieved per page
        type:        integer
        minimum:     10
        maximum:     200
        default:     30
        example:     50
      sort:
        description: Field to sort by
        enum: [entry_date, value]
        default: entry_date
        required: false
      sort_direction:
        description: Direction to sort by
        enum: [desc, asc]
        default: desc
        required: false
      fields:
        description: Specify the fields that you want to retrieve
        type:        string
        required:    false
        example:     entry_date
      date_start:
        type: date-only
        required: false
      date_end:
        type: date-only
        required: false
    responses:
      200:
        body:
          application/json:
            type: Water[]
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  post:
    displayName: water.create
    description: Create a new water resource
    securedBy: jwt 
    body:
      application/json:
        properties: # Don't need the other properties because JWT tells us
          entry_date:
            type: date-only # auto or set
            required: true
          value:
            type: integer # in metric
            required: true
    responses:
      200:
        body:
          application/json:
            type: Water
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  /{id}:
    uriParameters:
      id:
        type: string
    get:
        displayName: water.read
        description: Get water with _id
        securedBy: jwt
        queryParameters:
          fields:
            description: Specify the fields that you want to retrieve
            type:        string
            required:    false
            example:     start_datetime, end_datetime
        responses:
          200:
            body:
              application/json:
                type: Water
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    patch:
        displayName: water.update
        description: Update water with _id
        securedBy: jwt
        body:
          application/json:
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    delete:
        displayName: water.delete
        description: Delete water with _id
        securedBy: jwt
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array

/sleep:
  get:
    displayName: sleep.list
    description: Create a new sleep resource
    securedBy: jwt 
    queryParameters:
      page:
        description: Specify the page that you want to retrieve
        type:        integer
        required:    true
        example:     1
      per_page:
        description: Specify the amount of items that will be retrieved per page
        type:        integer
        minimum:     10
        maximum:     200
        default:     30
        example:     50
    responses:
      200:
        body:
          application/json:
            type: Sleep[]
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  post:
    displayName: sleep.create
    description: Create a new sleep resource
    securedBy: jwt 
    body:
      application/json:
        properties: # Don't need the other properties because JWT tells us
          start_datetime:
            type: datetime
            required: true
          end_datetime:
            type: datetime
            required: true
          quality:
            type: integer
            required: false
            minimum: 0
            maximum: 10
          notes:
            type: string
            required: false
    responses:
      200:
        body:
          application/json:
            type: Sleep
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  /{_id}:
    get:
        displayName: sleep.read
        description: Get sleep with _id
        securedBy: jwt
        responses:
          200:
            body:
              application/json:
                type: Sleep
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    patch:
        displayName: sleep.update
        description: Update sleep with _id
        securedBy: jwt
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    delete:
        displayName: sleep.delete
        description: Delete sleep with _id
        securedBy: jwt
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array

/mindfulness:
  get:
    displayName: mindfulness.list
    description: Create a new mindfulness resource
    securedBy: jwt
    queryParameters:
      page:
        description: Specify the page that you want to retrieve
        type:        integer
        required:    true
        example:     1
      per_page:
        description: Specify the amount of items that will be retrieved per page
        type:        integer
        minimum:     10
        maximum:     200
        default:     30
        example:     50
    responses:
      200:
        body:
          application/json:
            type: Mindfulness[]
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  post:
    displayName: mindfulness.create
    description: Create a new mindfulness resource
    securedBy: jwt 
    body:
      application/json:
        properties: # Don't need the other properties because JWT tells us
          start_datetime:
            type: datetime
            required: true
          end_datetime:
            type: datetime
            required: true
          notes:
            type: string
            required: false
    responses:
      200:
        body:
          application/json:
            type: Mindfulness
      400:
        body:
          application/json:
            properties:
              errors:
                type: array
  /{_id}:
    get:
        displayName: mindfulness.read
        description: Get mindfulness with _id
        securedBy: jwt
        queryParameters:
          fields:
            description: Specify the fields that you want to retrieve
            type:        string
            required:    false
            example:     start_datetime, end_datetime
        responses:
          200:
            body:
              application/json:
                type: Mindfulness
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    patch:
        displayName: mindfulness.update
        description: Update mindfulness with _id
        securedBy: jwt
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
    delete:
        displayName: mindfulness.delete
        description: Delete mindfulness with _id
        securedBy: jwt
        responses:
          202:
          400:
            body:
              application/json:
                properties:
                  errors:
                    type: array
