-- Users 
CREATE TABLE user (
	_id VARCHAR(14) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	first_name VARCHAR(40) NOT NULL,
	last_name VARCHAR(40) NOT NULL,
	birthdate DATE NOT NULL,
	email VARCHAR(40) NOT NULL,
	password VARCHAR(300) NOT NULL,
	height FLOAT UNSIGNED,
	unit ENUM('imperial', 'metric') NOT NULL DEFAULT 'imperial',
	UNIQUE (email),
	PRIMARY KEY (_id)
);
/**
 * TODO
 */
/*
CREATE TABLE goal (
	_id VARCHAR(14) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id VARCHAR(14) NOT NULL,
	PRIMARY KEY (_id),
	FOREIGN KEY (user_id) REFERENCES user(_id)
);

CREATE TABLE sleep (
	_id VARCHAR(14) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id VARCHAR(14) NOT NULL,
	PRIMARY KEY (_id),
	FOREIGN KEY (user_id) REFERENCES user(_id)
);

CREATE TABLE mindfulness (
	_id VARCHAR(14) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id VARCHAR(14) NOT NULL,
	PRIMARY KEY (_id),
	FOREIGN KEY (user_id) REFERENCES user(_id)
);
*/

CREATE TABLE weight (
	_id VARCHAR(14) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id VARCHAR(14) NOT NULL,
	entry_date DATE NOT NULL,
	value FLOAT NOT NULL,
	PRIMARY KEY (_id),
	FOREIGN KEY (user_id) REFERENCES user(_id)
);

CREATE TABLE water (
	_id VARCHAR(14) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id VARCHAR(14) NOT NULL,
	entry_date DATE NOT NULL,
	value FLOAT NOT NULL,
	PRIMARY KEY (_id),
	FOREIGN KEY (user_id) REFERENCES user(_id)
);
